version: '3.8'

services:
  dokemon-api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: javastraat/dokemon-api:latest
    container_name: dokemon-api
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      # Mount Docker socket for Docker management
      - /var/run/docker.sock:/var/run/docker.sock
      # Persistent storage for user data and logs
      - dokemon_data:/app/data
      # Optional: Mount custom config
      - ./config:/app/config:ro
      # Optional: Mount source code for development (uncomment for dev mode)
      # - ./src:/app/src:ro
    environment:
      - FLASK_ENV=production
      - DOKEMON_HOST=0.0.0.0
      - DOKEMON_PORT=9090
      - DOKEMON_DEBUG=false
      - SECRET_KEY=${SECRET_KEY:-dokemon-change-this-secret-key}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD:-admin}
      - DOKEMON_DOCKER_TIMEOUT=60
      - DOKEMON_VERSION_TIMEOUT=10
    networks:
      - dokemon-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.dokemon.service=api"
      - "com.dokemon.version=1.0.20250712"

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: dokemon-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - dokemon-api
    networks:
      - dokemon-network
    profiles:
      - production

volumes:
  dokemon_data:
    driver: local
    labels:
      - "com.dokemon.volume=data"

networks:
  dokemon-network:
    driver: bridge
    labels:
      - "com.dokemon.network=main"
